### ISSUE TITLE
Can't install alibi-detect with poetry because of long deps resolving 

### ISSUE THREAD

**Issue by smolendawid** [SeldonIO/alibi-detect#654]
With the following configuration
```
[tool.poetry]
name = "name"
version = "0.0.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = ">=3.7"
alibi-detect = "^0.10.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

after running `poetry install`, the resolving never ends.

Using Python 3.10 and poetry 1.1.14, M1 Mac.

Does anyone have a similar problem?

**Comment by jklaise** [comment]
I've just tested this (Python 3.10 and poetry 1.2.1) and the dependencies get resolved within a minute, although the installation the fails to install `llvmlite` (a dependency of `numba`) which is concerning.

**Comment by smolendawid** [comment]
Don't remember how, but I was in this place too. 

Also, maybe it's worth adding that `pip install alibi-detect==0.10.3` works.

**Comment by jklaise** [comment]
Yea, there's something fishy about the `poetry` dependency resolution as an older version of `numba` is pulled in (0.51.2) which in turn pulls in an old version of `llvmlite` (0.34.0) which breaks the build. `pip` correctly resolves to use the latest permitted dependencies. Will need to do some digging how `poetry` dependency resolution works and why it results in this strange, outdated list of deps.

**Comment by jklaise** [comment]
Alright, seems I have got to the bottom of the issue which is basically explained here: https://github.com/python-poetry/poetry/issues/5020#issuecomment-1142009971

In short, `numba 0.55.x` pins the Python version to `<3.11` which is in conflict with `poetry` specifying (by default) `^3.10` which is meant to represent `>=3.10, <4.0`. Now  `numba 0.56.x` seems to actually do away with the upper bound on the `python` version, hence it is now in agreement with the `poetry` specifier of `^3.10`.

The above can be verified by running the following:
```
poetry add "numba@^0.55"
```

```
Updating dependencies
Resolving dependencies... (0.7s)

The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - numba requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0
  - numba requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0
  - numba requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0

Because no versions of numba match >0.55,<0.55.1 || >0.55.1,<0.55.2 || >0.55.2,<0.56
 and numba (0.55.0) requires Python >=3.7,<3.11, numba is forbidden.
And because numba (0.55.1) requires Python >=3.7,<3.11, numba is forbidden.
So, because numba (0.55.2) requires Python >=3.7,<3.11
 and test depends on numba (^0.55), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For numba, a possible solution would be to set the `python` property to ">=3.10,<3.11"
    For numba, a possible solution would be to set the `python` property to ">=3.10,<3.11"
    For numba, a possible solution would be to set the `python` property to ">=3.10,<3.11"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

```

```
poetry add "numba@^0.56"
```

```
Updating dependencies
Resolving dependencies... (3.9s)

Writing lock file

Package operations: 12 installs, 0 updates, 0 removals

  • Installing llvmlite (0.39.1)
  • Installing catalogue (2.0.8)
  • Installing dill (0.3.5.1)
  • Installing matplotlib (3.6.1)
  • Installing numba (0.56.3)
  • Installing opencv-python (4.6.0.66)
  • Installing pandas (1.5.0)
  • Installing pydantic (1.10.2)
  • Installing scikit-image (0.19.3)
  • Installing scikit-learn (1.1.2)
  • Installing toml (0.10.2)
  • Installing transformers (4.23.1)
poetry add "numba@^0.56"  34.42s user 4.51s system 92% cpu 42.006 total
```

@smolendawid as a workaround, you could specify a tighter `python` version bound in `pyproject.toml`, e.g. using a [tilde](https://python-poetry.org/docs/dependency-specification/#tilde-requirements) such as `~3.10`. Would be good to hear if this change makes the resolution finish (I couldn't replicate resolution not finish at all - it always does, but results in the broken `numba` being pulled in).

**Comment by smolendawid** [comment]
Wow, that's a great investigation. Thanks a lot!

The numba issue is clarified, but alibi-detect requires numba <0.56.0 which still makes the installation impossible

Details:

with the following configuration:

```
[tool.poetry]
name = "test"
version = "0.0.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "~3.10"
numba = "^0.56"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```
after `poetry add alibi-detect`, the error is:

```
Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because no versions of alibi-detect match >0.10.3,<0.11.0
   and alibi-detect (0.10.3) depends on numba (>=0.50.0,<0.54.0 || >0.54.0,<0.56.0), alibi-detect (>=0.10.3,<0.11.0) requires numba (>=0.50.0,<0.54.0 || >0.54.0,<0.56.0).
  So, because name depends on both numba (^0.56) and alibi-detect (^0.10.3), version solving failed.
```

**Comment by smolendawid** [comment]
Thank you. After installing alibi-detect I had continuous problems with `llvmlite` and only after locking it to `llvmlite=="0.38.1"`  I was able to install more dependencies. Anyway, thanks a lot for help, the initial issue is solved.

**Comment by harishkashyap** [comment]
This doesn't seem to be resolved. Not sure why it is closed. This problem makes the library unusable.

**Comment by jklaise** [comment]
@harishkashyap sorry to hear you're still experiencing issues, have you followed the recommendation in the previous comment to specify the Python version via a tilde syntax instead of the (default) caret: https://github.com/SeldonIO/alibi-detect/issues/654#issuecomment-1281154236
